/**
 * ops-contractual-fixtures.ts — Casuísticas de referencia del SLA & CONTRACTUAL REGISTRY.
 *
 * ⚠️ FIXTURES DE MODELADO, NO CONTRATOS VALIDADOS.
 * Sirven para demostrar que el esquema soporta la realidad contractual de WG y
 * para ejercitar el motor de `ops-contractual.ts`. Todas nacen en estado
 * `borrador`: NINGUNA se usa para declarar cumplimiento hasta que Contratos las
 * valide contra el clausulado real.
 */

import type { ReglaSla } from "@/lib/ops-contractual";

export const AVISO_FIXTURES =
  "Reglas de referencia en estado borrador. Modelan casuísticas reales del negocio pero NO han sido validadas contra el clausulado. No se usan para calcular cumplimiento contractual.";

const base = {
  sociedad_wg_ejecutora: "Warranty Global",
  hard_limit: null,
  umbral_agregado: null,
  meses_consecutivos: null,
  ventana_garantia_dias: null,
  pausas_exclusiones: [] as string[],
  bonus: null,
  penalizacion: null,
  vigencia_desde: null,
  vigencia_hasta: null,
  estado_regla: "borrador" as const,
};

export const FIXTURES_REGISTRY: readonly ReglaSla[] = [
  // 1 · Cliente con SLA en horas laborables desde creación hasta primer contacto.
  {
    ...base,
    business_line: "Postventa electrodoméstico",
    cliente: "CARREFOUR",
    cliente_wg_patron: "CARREFOUR%",
    programa: "Garantía marca blanca",
    gama_familia: "Blanca",
    tipologia_servicio: "Reparación a domicilio",
    fase: "postventa",
    kpi: "Tiempo hasta primer contacto",
    evento_inicio: "creacion_ot",
    evento_fin: "primer_contacto",
    target: 24,
    unidad: "horas_laborables",
    calendario: "laborable_es",
    regla_medicion: "por_ot",
    ventana_medicion: "por_ot",
    imputabilidad: "wg",
    tipo_consecuencia: "malus",
    exposicion_estado: "identificada",
    fuente_contractual: "Fixture de modelado — pendiente de cotejar con el anexo de niveles de servicio",
    tipo_target: "contractual_target",
    notas: "Reloj en horas laborables: exige calendario laboral con festivos, hoy no disponible.",
  },

  // 2 · Cliente SIN SLA cuantificado en contrato.
  {
    ...base,
    business_line: "Postventa electrodoméstico",
    cliente: "NEUMESSE, S.L.",
    cliente_wg_patron: "NEUMESSE%",
    programa: "Servicio técnico general",
    gama_familia: null,
    tipologia_servicio: null,
    fase: "postventa",
    kpi: "Plazo de cierre",
    evento_inicio: "creacion_ot",
    evento_fin: "cierre",
    target: null,
    unidad: "dias_naturales",
    calendario: "natural",
    regla_medicion: "por_ot",
    ventana_medicion: "por_ot",
    imputabilidad: "por_determinar",
    tipo_consecuencia: "riesgo_sin_cuantificar",
    exposicion_estado: "pendiente_cuantificar",
    fuente_contractual: "Fixture de modelado — contrato sin nivel de servicio explícito",
    tipo_target: "contractual_target",
    notas: "Sin SLA cuantificado: el motor devuelve no evaluable. Prohibido aplicar el ≤20d interno como si fuese contractual.",
  },

  // 3 · Bonus / malus sobre % de OTs cerradas en plazo.
  {
    ...base,
    business_line: "Seguros y garantías extendidas",
    cliente: "ASSURANT",
    cliente_wg_patron: "ASSURANT%",
    programa: "Garantía extendida",
    gama_familia: null,
    tipologia_servicio: "Reparación",
    fase: "postventa",
    kpi: "% de OTs cerradas en plazo",
    evento_inicio: "creacion_ot",
    evento_fin: "cierre",
    target: 15,
    unidad: "dias_naturales",
    calendario: "natural",
    regla_medicion: "porcentaje_ots",
    umbral_agregado: 0.9,
    ventana_medicion: "mes",
    imputabilidad: "wg",
    bonus: { condicion: "pct_en_plazo >= 0.95", base: "facturación mensual", cuantia: "pendiente" },
    penalizacion: { condicion: "pct_en_plazo < 0.90", base: "facturación mensual", cuantia: "pendiente" },
    tipo_consecuencia: "pct_facturacion_mensual",
    exposicion_estado: "pendiente_cuantificar",
    fuente_contractual: "Fixture de modelado — esquema bonus/malus mensual",
    tipo_target: "contractual_target",
    notas: "Regla agregada mensual: el denominador son las OTs evaluables del mes, no todas las OTs.",
  },

  // 4 · Cliente con exclusiones y pausas declaradas.
  {
    ...base,
    business_line: "Postventa electrodoméstico",
    cliente: "CECOTEC INNOVACIONES, S.L.U.",
    cliente_wg_patron: "CECOTEC%",
    programa: "Garantía fabricante",
    gama_familia: "PAE",
    tipologia_servicio: "Reparación en taller",
    fase: "postventa",
    kpi: "Plazo de reparación excluyendo esperas ajenas",
    evento_inicio: "recogida",
    evento_fin: "reparacion",
    target: 10,
    unidad: "dias_naturales",
    calendario: "natural",
    regla_medicion: "por_ot",
    ventana_medicion: "por_ot",
    pausas_exclusiones: ["espera_repuesto", "cliente_no_localizable", "autorizacion_presupuesto"],
    imputabilidad: "mixta",
    tipo_consecuencia: "malus",
    exposicion_estado: "pendiente_cuantificar",
    fuente_contractual: "Fixture de modelado — cláusula de exclusiones de reloj",
    tipo_target: "contractual_target",
    notas: "El reloj solo se pausa por los motivos declarados. Hoy no hay historial de estados para medir esas pausas.",
  },

  // 5 · Reparación no pagada si se supera el límite duro.
  {
    ...base,
    business_line: "Retail gran distribución",
    cliente: "ALCAMPO",
    cliente_wg_patron: "ALCAMPO%",
    programa: "Postventa tienda",
    gama_familia: "Blanca",
    tipologia_servicio: "Reparación a domicilio",
    fase: "postventa",
    kpi: "Plazo máximo de reparación",
    evento_inicio: "creacion_ot",
    evento_fin: "reparacion",
    target: 10,
    hard_limit: 20,
    unidad: "dias_laborables",
    calendario: "laborable_es",
    regla_medicion: "por_ot",
    ventana_medicion: "por_ot",
    imputabilidad: "wg",
    tipo_consecuencia: "reparacion_no_pagada",
    exposicion_estado: "cuantificable",
    fuente_contractual: "Fixture de modelado — objetivo con límite duro",
    tipo_target: "contractual_hard_limit",
    notas: "Dos umbrales distintos: objetivo (10 dl) y límite duro (20 dl) con consecuencia económica directa.",
  },

  // 6 · Coste de la baja asumido si se supera el plazo.
  {
    ...base,
    business_line: "Retail gran distribución",
    cliente: "ELECTRO DEPOT ESPAÑA S.L.U",
    cliente_wg_patron: "ELECTRO DEPOT%",
    programa: "Garantía tienda",
    gama_familia: null,
    tipologia_servicio: "Reparación",
    fase: "postventa",
    kpi: "Plazo antes de sustitución",
    evento_inicio: "creacion_ot",
    evento_fin: "cierre",
    target: 21,
    unidad: "dias_naturales",
    calendario: "natural",
    regla_medicion: "por_ot",
    ventana_medicion: "por_ot",
    imputabilidad: "wg",
    tipo_consecuencia: "coste_baja",
    exposicion_estado: "cuantificable",
    fuente_contractual: "Fixture de modelado — cláusula de sustitución por demora",
    tipo_target: "contractual_hard_limit",
    notas: "Superado el plazo, el aparato se da de baja y el coste lo asume WG.",
  },

  // 7 · Repeat repair dentro de ventana de garantía.
  {
    ...base,
    business_line: "Retail profesional",
    cliente: "MAKRO",
    cliente_wg_patron: "MAKRO%",
    programa: "Mantenimiento profesional",
    gama_familia: "Professional",
    tipologia_servicio: "Reparación",
    fase: "postventa",
    kpi: "Reincidencia en garantía de reparación",
    evento_inicio: "cierre_anterior",
    evento_fin: "creacion_ot",
    target: 0,
    unidad: "recuento",
    calendario: "natural",
    regla_medicion: "recurrencia",
    ventana_medicion: "por_ot",
    ventana_garantia_dias: 90,
    imputabilidad: "wg",
    tipo_consecuencia: "rework_absorbido",
    exposicion_estado: "cuantificable",
    fuente_contractual: "Fixture de modelado — garantía de reparación 90 días",
    tipo_target: "contractual_target",
    notas: "Requiere trazar aparato entre OTs: hoy no existe enlace ot_anterior.",
  },

  // 8 · Incumplimiento por meses consecutivos.
  {
    ...base,
    business_line: "E-commerce",
    cliente: "PC COMPONENTES",
    cliente_wg_patron: "PC COMPONENTES%",
    programa: "Postventa e-commerce",
    gama_familia: null,
    tipologia_servicio: "Reparación",
    fase: "postventa",
    kpi: "% mensual de OTs en plazo sostenido",
    evento_inicio: "creacion_ot",
    evento_fin: "cierre",
    target: 20,
    unidad: "dias_naturales",
    calendario: "natural",
    regla_medicion: "meses_consecutivos",
    umbral_agregado: 0.85,
    ventana_medicion: "mes",
    meses_consecutivos: 3,
    imputabilidad: "wg",
    tipo_consecuencia: "incumplimiento_grave",
    exposicion_estado: "identificada",
    fuente_contractual: "Fixture de modelado — cláusula de resolución por incumplimiento reiterado",
    tipo_target: "contractual_target",
    notas: "Tres meses consecutivos por debajo del 85% habilitan resolución del contrato.",
  },

  // 9 · Preventa / instalación con reloj en horas naturales.
  {
    ...base,
    business_line: "Instalación",
    cliente: "METRO MARKETS GMBH",
    cliente_wg_patron: "METRO MARKETS%",
    programa: "Instalación de producto",
    gama_familia: "Clima",
    tipologia_servicio: "Instalación",
    fase: "preventa",
    kpi: "Tiempo de respuesta al cliente final",
    evento_inicio: "creacion_ot",
    evento_fin: "respuesta",
    target: 48,
    unidad: "horas_naturales",
    calendario: "natural",
    regla_medicion: "por_ot",
    ventana_medicion: "por_ot",
    imputabilidad: "wg",
    tipo_consecuencia: "malus",
    exposicion_estado: "pendiente_cuantificar",
    fuente_contractual: "Fixture de modelado — acuerdo de instalación",
    tipo_target: "contractual_target",
    notas: "Fase preventa: el ciclo de instalación no comparte eventos con el de reparación.",
  },

  // 10 · Obligación de reporting (no medible por OT).
  {
    ...base,
    business_line: "Postventa electrodoméstico",
    cliente: "ELECTRODOMESTICOS SAUBER",
    cliente_wg_patron: "SAUBER%",
    programa: "Garantía fabricante",
    gama_familia: null,
    tipologia_servicio: null,
    fase: "postventa",
    kpi: "Entrega de reporting mensual",
    evento_inicio: "otro",
    evento_fin: "otro",
    target: 5,
    unidad: "dias_laborables",
    calendario: "laborable_es",
    regla_medicion: "reporting",
    ventana_medicion: "mes",
    imputabilidad: "wg",
    tipo_consecuencia: "riesgo_sin_cuantificar",
    exposicion_estado: "identificada",
    fuente_contractual: "Fixture de modelado — obligación de reporting",
    tipo_target: "contractual_target",
    notas: "Obligación de servicio no medible sobre ops_fact_ot: se controla fuera del dato operativo.",
  },
] as const;
