/**
 * Listado ampliado de localidades por provincia con su código postal
 * "cabecera". Cubre los municipios principales y cabeceras de comarca de
 * cada provincia (≈ 1.500 entradas) para que el colaborador pueda excluir
 * localidades concretas dentro de su zona de cobertura.
 *
 * Para las grandes capitales (Madrid, Barcelona, Valencia, Sevilla, Málaga,
 * Zaragoza, Bilbao) se desglosa el municipio capital en distritos / zonas
 * (centro y periferia) para permitir exclusiones más finas (p.ej. atender
 * "Madrid Centro" pero no "Vallecas").
 *
 * Nota: España tiene >8.000 municipios. Esta lista no es exhaustiva, pero
 * incluye prácticamente todos los >5.000 habitantes y todas las cabeceras
 * comarcales relevantes para servicios técnicos / SAT.
 */

export interface Localidad {
  name: string;
  cp: string;
}

export const LOCALIDADES_BY_PROVINCE: Record<string, Localidad[]> = {
  // ============= ANDALUCÍA =============
  "04": [ // Almería
    // ───── 1) Almería capital ─────
    { name: "Almería Capital · Centro", cp: "04001" },
    { name: "Almería Capital · Nueva Andalucía", cp: "04007" },
    { name: "Almería Capital · Zapillo", cp: "04007" },
    { name: "Almería Capital · Ciudad Jardín", cp: "04006" },
    { name: "Almería Capital · El Alquián", cp: "04130" },
    { name: "Almería Capital · Retamar", cp: "04131" },

    // ───── 2) Área metropolitana (≤20–25 km) ─────
    // 2.1 Poniente cercano
    { name: "AL Á. Metro Poniente · Roquetas de Mar", cp: "04740" },
    { name: "AL Á. Metro Poniente · Vícar", cp: "04738" },
    { name: "AL Á. Metro Poniente · La Mojonera", cp: "04745" },
    // 2.2 Norte / área cercana
    { name: "AL Á. Metro Norte · Huércal de Almería", cp: "04230" },
    { name: "AL Á. Metro Norte · Viator", cp: "04240" },

    // ───── 3) Resto provincia de Almería ─────
    // 3.1 Poniente ampliado (25–40 km)
    { name: "AL Poniente Ampliado · El Ejido", cp: "04700" },
    { name: "AL Poniente Ampliado · Adra", cp: "04770" },
    // 3.2 Levante
    { name: "AL Levante · Vera", cp: "04620" },
    { name: "AL Levante · Mojácar", cp: "04638" },
    { name: "AL Levante · Garrucha", cp: "04630" },
    // 3.3 Interior
    { name: "AL Interior · Huércal-Overa", cp: "04600" },
    { name: "AL Interior · Albox", cp: "04800" },
  ],
  "11": [ // Cádiz
    // ───── 1.1 Cádiz capital (barrios) ─────
    { name: "Cádiz Capital · Centro", cp: "11001" },
    { name: "Cádiz Capital · Extramuros", cp: "11008" },
    { name: "Cádiz Capital · La Viña", cp: "11002" },
    { name: "Cádiz Capital · El Mentidero", cp: "11001" },
    { name: "Cádiz Capital · Santa María", cp: "11005" },
    { name: "Cádiz Capital · Puntales", cp: "11011" },
    { name: "Cádiz Capital · Loreto", cp: "11010" },
    { name: "Cádiz Capital · Cerro del Moro", cp: "11012" },
    { name: "Cádiz Capital · Guillén Moreno", cp: "11008" },

    // ───── 1.2 Área metropolitana ─────
    // 1.2.1 Bahía de Cádiz
    { name: "CA Á. Metro Bahía · San Fernando", cp: "11100" },
    { name: "CA Á. Metro Bahía · Puerto Real", cp: "11510" },
    { name: "CA Á. Metro Bahía · El Puerto de Santa María", cp: "11500" },
    { name: "CA Á. Metro Bahía · Chiclana de la Frontera", cp: "11130" },

    // ───── 1.3 Resto provincia de Cádiz ─────
    // 1.3.1 Jerez
    { name: "CA Jerez · Jerez de la Frontera", cp: "11401" },
    // 1.3.2 Costa noroeste
    { name: "CA Costa Noroeste · Sanlúcar de Barrameda", cp: "11540" },
    { name: "CA Costa Noroeste · Rota", cp: "11520" },
    { name: "CA Costa Noroeste · Chipiona", cp: "11550" },
    // 1.3.3 Campo de Gibraltar
    { name: "CA Campo de Gibraltar · Algeciras", cp: "11201" },
    { name: "CA Campo de Gibraltar · La Línea de la Concepción", cp: "11300" },
    { name: "CA Campo de Gibraltar · San Roque", cp: "11360" },
    { name: "CA Campo de Gibraltar · Los Barrios", cp: "11370" },
  ],
  "14": [ // Córdoba
    // ───── 1.1 Córdoba capital (distritos) ─────
    { name: "Córdoba Capital · Centro", cp: "14002" },
    { name: "Córdoba Capital · Poniente Norte", cp: "14011" },
    { name: "Córdoba Capital · Poniente Sur", cp: "14013" },
    { name: "Córdoba Capital · Norte-Sierra", cp: "14012" },
    { name: "Córdoba Capital · Sureste", cp: "14014" },
    { name: "Córdoba Capital · Sur", cp: "14010" },
    { name: "Córdoba Capital · Levante", cp: "14006" },
    { name: "Córdoba Capital · Noroeste", cp: "14011" },
    { name: "Córdoba Capital · Fuensanta", cp: "14010" },
    { name: "Córdoba Capital · El Brillante", cp: "14012" },

    // ───── 1.2 Área metropolitana ─────
    // 1.2.1 Oeste / Valle del Guadalquivir
    { name: "CO Á. Metro Oeste · Almodóvar del Río", cp: "14720" },
    { name: "CO Á. Metro Oeste · Posadas", cp: "14730" },
    // 1.2.2 Sur cercano
    { name: "CO Á. Metro Sur · La Carlota", cp: "14100" },
    { name: "CO Á. Metro Sur · Guadalcázar", cp: "14112" },
    // 1.2.3 Este cercano
    { name: "CO Á. Metro Este · El Carpio", cp: "14620" },
    { name: "CO Á. Metro Este · Villafranca de Córdoba", cp: "14420" },

    // ───── 1.3 Resto provincia de Córdoba ─────
    // 1.3.1 Sur (Subbética)
    { name: "CO Subbética · Lucena", cp: "14900" },
    { name: "CO Subbética · Cabra", cp: "14940" },
    { name: "CO Subbética · Priego de Córdoba", cp: "14800" },
    // 1.3.2 Campiña
    { name: "CO Campiña · Puente Genil", cp: "14500" },
    { name: "CO Campiña · Montilla", cp: "14550" },
    { name: "CO Campiña · Aguilar de la Frontera", cp: "14920" },
    // 1.3.3 Norte (Los Pedroches / Valle del Guadiato)
    { name: "CO Norte · Pozoblanco", cp: "14400" },
    { name: "CO Norte · Peñarroya-Pueblonuevo", cp: "14200" },
  ],
  "18": [ // Granada
    // ───── 1.1 Granada capital (distritos) ─────
    { name: "Granada Capital · Centro", cp: "18001" },
    { name: "Granada Capital · Albaicín", cp: "18010" },
    { name: "Granada Capital · Sacromonte", cp: "18010" },
    { name: "Granada Capital · Realejo", cp: "18009" },
    { name: "Granada Capital · Zaidín", cp: "18007" },
    { name: "Granada Capital · Chana", cp: "18015" },
    { name: "Granada Capital · Norte", cp: "18013" },
    { name: "Granada Capital · Genil", cp: "18006" },
    { name: "Granada Capital · Ronda", cp: "18004" },
    { name: "Granada Capital · Beiro", cp: "18011" },

    // ───── 1.2 Área metropolitana ─────
    // 1.2.1 Cinturón Oeste
    { name: "GR Á. Metro Oeste · Santa Fe", cp: "18320" },
    { name: "GR Á. Metro Oeste · Atarfe", cp: "18230" },
    // 1.2.2 Cinturón Sur
    { name: "GR Á. Metro Sur · Armilla", cp: "18100" },
    { name: "GR Á. Metro Sur · Ogíjares", cp: "18151" },
    { name: "GR Á. Metro Sur · La Zubia", cp: "18140" },
    // 1.2.3 Cinturón Norte
    { name: "GR Á. Metro Norte · Maracena", cp: "18200" },
    { name: "GR Á. Metro Norte · Albolote", cp: "18220" },
    { name: "GR Á. Metro Norte · Peligros", cp: "18210" },

    // ───── 1.3 Resto provincia de Granada ─────
    // 1.3.1 Costa Tropical
    { name: "GR Costa Tropical · Motril", cp: "18600" },
    { name: "GR Costa Tropical · Salobreña", cp: "18680" },
    { name: "GR Costa Tropical · Almuñécar", cp: "18690" },
    // 1.3.2 Norte / interior
    { name: "GR Norte Interior · Guadix", cp: "18500" },
    { name: "GR Norte Interior · Baza", cp: "18800" },
    // 1.3.3 Alpujarra
    { name: "GR Alpujarra · Órgiva", cp: "18400" },
    { name: "GR Alpujarra · Lanjarón", cp: "18420" },
  ],
  "21": [ // Huelva
    // ───── 1.1 Huelva capital (barrios) ─────
    { name: "Huelva Capital · Centro", cp: "21001" },
    { name: "Huelva Capital · Isla Chica", cp: "21002" },
    { name: "Huelva Capital · El Matadero", cp: "21003" },
    { name: "Huelva Capital · Molino de la Vega", cp: "21006" },
    { name: "Huelva Capital · Pérez Cubillas", cp: "21006" },
    { name: "Huelva Capital · Verdeluz", cp: "21005" },
    { name: "Huelva Capital · La Orden", cp: "21006" },
    { name: "Huelva Capital · Fuentepiña", cp: "21007" },
    { name: "Huelva Capital · El Carmen", cp: "21002" },

    // ───── 1.2 Área metropolitana ─────
    // 1.2.1 Cinturón cercano
    { name: "HU Á. Metro Cercano · Punta Umbría", cp: "21100" },
    { name: "HU Á. Metro Cercano · Aljaraque", cp: "21110" },
    { name: "HU Á. Metro Cercano · Gibraleón", cp: "21500" },
    { name: "HU Á. Metro Cercano · Palos de la Frontera", cp: "21810" },
    { name: "HU Á. Metro Cercano · Moguer", cp: "21800" },

    // ───── 1.3 Resto provincia de Huelva ─────
    // 1.3.1 Costa
    { name: "HU Costa · Lepe", cp: "21440" },
    { name: "HU Costa · Isla Cristina", cp: "21410" },
    { name: "HU Costa · Ayamonte", cp: "21400" },
    // 1.3.2 Condado
    { name: "HU Condado · Almonte", cp: "21730" },
    { name: "HU Condado · La Palma del Condado", cp: "21700" },
    // 1.3.3 Sierra
    { name: "HU Sierra · Aracena", cp: "21200" },
    { name: "HU Sierra · Cortegana", cp: "21230" },
    { name: "HU Sierra · Jabugo", cp: "21290" },
  ],
  "23": [ // Jaén
    // ───── 1.1 Jaén capital (barrios) ─────
    { name: "Jaén Capital · Centro", cp: "23001" },
    { name: "Jaén Capital · Peñamefécit", cp: "23004" },
    { name: "Jaén Capital · San Ildefonso", cp: "23007" },
    { name: "Jaén Capital · La Magdalena", cp: "23004" },
    { name: "Jaén Capital · Expansión Norte", cp: "23009" },
    { name: "Jaén Capital · Polígono del Valle", cp: "23009" },

    // ───── 1.2 Área metropolitana ─────
    // 1.2.1 Cinturón cercano
    { name: "JA Á. Metro Cercano · La Guardia de Jaén", cp: "23170" },
    { name: "JA Á. Metro Cercano · Mancha Real", cp: "23100" },
    { name: "JA Á. Metro Cercano · Torredelcampo", cp: "23640" },
    { name: "JA Á. Metro Cercano · Torredonjimeno", cp: "23650" },
    { name: "JA Á. Metro Cercano · Martos", cp: "23600" },

    // ───── 1.3 Resto provincia de Jaén ─────
    // 1.3.1 Corredor central
    { name: "JA Corredor Central · Linares", cp: "23700" },
    { name: "JA Corredor Central · Andújar", cp: "23740" },
    { name: "JA Corredor Central · Bailén", cp: "23710" },
    // 1.3.2 La Loma
    { name: "JA La Loma · Úbeda", cp: "23400" },
    { name: "JA La Loma · Baeza", cp: "23440" },
    // 1.3.3 Sierra
    { name: "JA Sierra · La Carolina", cp: "23200" },
    { name: "JA Sierra · Cazorla", cp: "23470" },
  ],
  "29": [ // Málaga
    // — Málaga capital: distritos centrales —
    { name: "Málaga · Centro", cp: "29001" },
    { name: "Málaga · Ensanche-Soho", cp: "29005" },
    { name: "Málaga · La Malagueta", cp: "29016" },
    // — Málaga capital: distritos periféricos —
    { name: "Málaga · Este (Pedregalejo, El Palo)", cp: "29017" },
    { name: "Málaga · Ciudad Jardín", cp: "29014" },
    { name: "Málaga · Bailén-Miraflores", cp: "29009" },
    { name: "Málaga · Palma-Palmilla", cp: "29011" },
    { name: "Málaga · Cruz de Humilladero", cp: "29004" },
    { name: "Málaga · Carretera de Cádiz", cp: "29006" },
    { name: "Málaga · Churriana", cp: "29140" },
    { name: "Málaga · Campanillas", cp: "29590" },
    { name: "Málaga · Puerto de la Torre", cp: "29190" },
    { name: "Málaga · Teatinos-Universidad", cp: "29010" },
    { name: "Marbella", cp: "29600" },
    { name: "Mijas", cp: "29650" },
    { name: "Fuengirola", cp: "29640" },
    { name: "Torremolinos", cp: "29620" },
    { name: "Vélez-Málaga", cp: "29700" },
    { name: "Estepona", cp: "29680" },
    { name: "Benalmádena", cp: "29630" },
    { name: "Antequera", cp: "29200" },
    { name: "Ronda", cp: "29400" },
    { name: "Rincón de la Victoria", cp: "29730" },
    { name: "Alhaurín de la Torre", cp: "29130" },
    { name: "Alhaurín el Grande", cp: "29120" },
    { name: "Coín", cp: "29100" },
    { name: "Cártama", cp: "29570" },
    { name: "Nerja", cp: "29780" },
    { name: "Torrox", cp: "29770" },
    { name: "Manilva", cp: "29691" },
    { name: "Álora", cp: "29500" },
    { name: "Archidona", cp: "29300" },
    { name: "Pizarra", cp: "29560" },
    { name: "Casares", cp: "29690" },
    { name: "San Pedro de Alcántara", cp: "29670" },
    { name: "Algarrobo", cp: "29750" },
    { name: "Benahavís", cp: "29679" },
  ],
  "41": [ // Sevilla
    // ───── 1) Sevilla Capital · 11 distritos ─────
    { name: "Sevilla Capital · Casco Antiguo", cp: "41004" },
    { name: "Sevilla Capital · Triana", cp: "41010" },
    { name: "Sevilla Capital · Los Remedios", cp: "41011" },
    { name: "Sevilla Capital · Nervión", cp: "41005" },
    { name: "Sevilla Capital · Sur", cp: "41012" },
    { name: "Sevilla Capital · Macarena", cp: "41008" },
    { name: "Sevilla Capital · Norte", cp: "41015" },
    { name: "Sevilla Capital · Este-Alcosa-Torreblanca", cp: "41020" },
    { name: "Sevilla Capital · Cerro-Amate", cp: "41006" },
    { name: "Sevilla Capital · San Pablo-Santa Justa", cp: "41007" },
    { name: "Sevilla Capital · Bellavista-La Palmera", cp: "41013" },

    // ───── 2) Área metropolitana ─────
    // 2.1 Norte
    { name: "SE Á. Metro Norte · La Rinconada", cp: "41309" },
    { name: "SE Á. Metro Norte · Alcalá del Río", cp: "41200" },
    // 2.2 Oeste / Aljarafe
    { name: "SE Á. Metro Oeste · Camas", cp: "41900" },
    { name: "SE Á. Metro Oeste · Tomares", cp: "41940" },
    { name: "SE Á. Metro Oeste · Castilleja de la Cuesta", cp: "41950" },
    { name: "SE Á. Metro Oeste · Mairena del Aljarafe", cp: "41927" },
    { name: "SE Á. Metro Oeste · Bormujos", cp: "41930" },
    { name: "SE Á. Metro Oeste · San Juan de Aznalfarache", cp: "41920" },
    { name: "SE Á. Metro Oeste · Coria del Río", cp: "41100" },
    // 2.3 Sur
    { name: "SE Á. Metro Sur · Dos Hermanas", cp: "41700" },
    { name: "SE Á. Metro Sur · Los Palacios y Villafranca", cp: "41720" },
    // 2.4 Este
    { name: "SE Á. Metro Este · Alcalá de Guadaíra", cp: "41500" },

    // ───── 3) Resto provincia Sevilla ─────
    // 3.1 Sierra Norte
    { name: "SE Sierra Norte · Cazalla de la Sierra", cp: "41370" },
    { name: "SE Sierra Norte · Constantina", cp: "41450" },
    { name: "SE Sierra Norte · El Pedroso", cp: "41360" },
    // 3.2 Campiña / Este
    { name: "SE Campiña Este · Écija", cp: "41400" },
    { name: "SE Campiña Este · Osuna", cp: "41640" },
    { name: "SE Campiña Este · Marchena", cp: "41620" },
    // 3.3 Sur profundo
    { name: "SE Sur Profundo · Utrera", cp: "41710" },
    { name: "SE Sur Profundo · Lebrija", cp: "41740" },
  ],

  // ============= ARAGÓN =============
  "22": [ // Huesca
    { name: "Huesca", cp: "22001" },
    { name: "Monzón", cp: "22400" },
    { name: "Barbastro", cp: "22300" },
    { name: "Fraga", cp: "22520" },
    { name: "Jaca", cp: "22700" },
    { name: "Sabiñánigo", cp: "22600" },
    { name: "Binéfar", cp: "22500" },
    { name: "Sariñena", cp: "22200" },
    { name: "Tamarite de Litera", cp: "22550" },
    { name: "Graus", cp: "22430" },
    { name: "Almudévar", cp: "22270" },
    { name: "Ayerbe", cp: "22800" },
    { name: "Boltaña", cp: "22340" },
    { name: "Aínsa", cp: "22330" },
  ],
  "44": [ // Teruel
    { name: "Teruel", cp: "44001" },
    { name: "Alcañiz", cp: "44600" },
    { name: "Andorra", cp: "44500" },
    { name: "Calanda", cp: "44570" },
    { name: "Utrillas", cp: "44760" },
    { name: "Calamocha", cp: "44200" },
    { name: "Monreal del Campo", cp: "44300" },
    { name: "Híjar", cp: "44530" },
    { name: "Mora de Rubielos", cp: "44400" },
    { name: "Cella", cp: "44370" },
    { name: "Albarracín", cp: "44100" },
    { name: "Valderrobres", cp: "44580" },
  ],
  "50": [ // Zaragoza
    // — Zaragoza capital: distritos centrales —
    { name: "Zaragoza · Centro", cp: "50001" },
    { name: "Zaragoza · Casco Histórico", cp: "50003" },
    { name: "Zaragoza · Universidad", cp: "50009" },
    { name: "Zaragoza · La Magdalena-San Pablo", cp: "50002" },
    // — Zaragoza capital: distritos periféricos —
    { name: "Zaragoza · Delicias", cp: "50010" },
    { name: "Zaragoza · Las Fuentes", cp: "50013" },
    { name: "Zaragoza · La Almozara", cp: "50003" },
    { name: "Zaragoza · Oliver-Valdefierro", cp: "50011" },
    { name: "Zaragoza · Torrero-La Paz", cp: "50007" },
    { name: "Zaragoza · El Rabal (Actur)", cp: "50015" },
    { name: "Zaragoza · Santa Isabel", cp: "50016" },
    { name: "Zaragoza · Casablanca", cp: "50012" },
    { name: "Zaragoza · Miralbueno", cp: "50011" },
    { name: "Calatayud", cp: "50300" },
    { name: "Utebo", cp: "50180" },
    { name: "Ejea de los Caballeros", cp: "50600" },
    { name: "Tarazona", cp: "50500" },
    { name: "Caspe", cp: "50700" },
    { name: "La Almunia de Doña Godina", cp: "50100" },
    { name: "Cuarte de Huerva", cp: "50410" },
    { name: "Zuera", cp: "50800" },
    { name: "Borja", cp: "50540" },
    { name: "Cariñena", cp: "50400" },
    { name: "Daroca", cp: "50360" },
    { name: "Épila", cp: "50290" },
    { name: "Tauste", cp: "50660" },
    { name: "Alagón", cp: "50630" },
    { name: "María de Huerva", cp: "50430" },
    { name: "Pina de Ebro", cp: "50750" },
    { name: "Pedrola", cp: "50690" },
    { name: "Casetas", cp: "50620" },
  ],

  // ============= ASTURIAS =============
  "33": [
    { name: "Oviedo", cp: "33001" },
    { name: "Gijón", cp: "33201" },
    { name: "Avilés", cp: "33400" },
    { name: "Siero", cp: "33510" },
    { name: "Langreo", cp: "33930" },
    { name: "Mieres", cp: "33600" },
    { name: "Castrillón", cp: "33450" },
    { name: "Llanera", cp: "33420" },
    { name: "San Martín del Rey Aurelio", cp: "33936" },
    { name: "Villaviciosa", cp: "33300" },
    { name: "Cangas del Narcea", cp: "33800" },
    { name: "Cangas de Onís", cp: "33550" },
    { name: "Llanes", cp: "33500" },
    { name: "Tineo", cp: "33870" },
    { name: "Pravia", cp: "33120" },
    { name: "Grado", cp: "33820" },
    { name: "Lena", cp: "33630" },
    { name: "Navia", cp: "33710" },
    { name: "Luarca (Valdés)", cp: "33700" },
    { name: "Corvera de Asturias", cp: "33416" },
    { name: "Carreño (Candás)", cp: "33430" },
    { name: "Nava", cp: "33520" },
    { name: "Pola de Laviana", cp: "33980" },
    { name: "Piloña (Infiesto)", cp: "33530" },
    { name: "Ribadesella", cp: "33560" },
  ],

  // ============= ISLAS BALEARES =============
  "07": [
    { name: "Palma", cp: "07001" },
    { name: "Calvià", cp: "07181" },
    { name: "Manacor", cp: "07500" },
    { name: "Inca", cp: "07300" },
    { name: "Ibiza (Eivissa)", cp: "07800" },
    { name: "Santa Eulària des Riu", cp: "07840" },
    { name: "Mahón (Maó)", cp: "07701" },
    { name: "Ciutadella de Menorca", cp: "07760" },
    { name: "Marratxí", cp: "07141" },
    { name: "Llucmajor", cp: "07620" },
    { name: "Sant Antoni de Portmany", cp: "07820" },
    { name: "Pollença", cp: "07460" },
    { name: "Felanitx", cp: "07200" },
    { name: "Alcúdia", cp: "07400" },
    { name: "Sóller", cp: "07100" },
    { name: "Sant Josep de sa Talaia", cp: "07830" },
    { name: "Capdepera", cp: "07580" },
    { name: "Andratx", cp: "07150" },
    { name: "Son Servera", cp: "07550" },
    { name: "Santanyí", cp: "07650" },
    { name: "Artà", cp: "07570" },
    { name: "Binissalem", cp: "07350" },
    { name: "Sa Pobla", cp: "07420" },
    { name: "Muro", cp: "07440" },
    { name: "Alaior", cp: "07730" },
    { name: "Es Mercadal", cp: "07740" },
    { name: "Sant Lluís", cp: "07710" },
    { name: "Formentera (Sant Francesc)", cp: "07860" },
  ],

  // ============= CANARIAS =============
  "35": [ // Las Palmas
    { name: "Las Palmas de Gran Canaria", cp: "35001" },
    { name: "Telde", cp: "35200" },
    { name: "Santa Lucía de Tirajana", cp: "35110" },
    { name: "San Bartolomé de Tirajana", cp: "35100" },
    { name: "Arrecife", cp: "35500" },
    { name: "Puerto del Rosario", cp: "35600" },
    { name: "Arucas", cp: "35400" },
    { name: "Ingenio", cp: "35250" },
    { name: "Gáldar", cp: "35460" },
    { name: "Santa María de Guía", cp: "35450" },
    { name: "Mogán", cp: "35140" },
    { name: "Agüimes", cp: "35260" },
    { name: "La Oliva (Corralejo)", cp: "35640" },
    { name: "Pájara (Morro Jable)", cp: "35625" },
    { name: "Tías", cp: "35510" },
    { name: "Teguise", cp: "35530" },
    { name: "Yaiza", cp: "35570" },
    { name: "San Bartolomé (Lanzarote)", cp: "35550" },
    { name: "Antigua", cp: "35630" },
    { name: "Tuineje (Gran Tarajal)", cp: "35620" },
    { name: "Vega de San Mateo", cp: "35320" },
    { name: "Valsequillo", cp: "35217" },
    { name: "Firgas", cp: "35430" },
    { name: "Teror", cp: "35330" },
  ],
  "38": [ // S.C. Tenerife
    { name: "Santa Cruz de Tenerife", cp: "38001" },
    { name: "San Cristóbal de La Laguna", cp: "38201" },
    { name: "Arona", cp: "38640" },
    { name: "Adeje", cp: "38670" },
    { name: "Granadilla de Abona", cp: "38600" },
    { name: "La Orotava", cp: "38300" },
    { name: "Los Realejos", cp: "38410" },
    { name: "Puerto de la Cruz", cp: "38400" },
    { name: "Santa Cruz de La Palma", cp: "38700" },
    { name: "Icod de los Vinos", cp: "38430" },
    { name: "Candelaria", cp: "38530" },
    { name: "Tacoronte", cp: "38350" },
    { name: "Güímar", cp: "38500" },
    { name: "Los Llanos de Aridane", cp: "38760" },
    { name: "El Rosario", cp: "38108" },
    { name: "La Victoria de Acentejo", cp: "38380" },
    { name: "La Matanza de Acentejo", cp: "38379" },
    { name: "El Sauzal", cp: "38360" },
    { name: "Buenavista del Norte", cp: "38480" },
    { name: "Garachico", cp: "38450" },
    { name: "San Miguel de Abona", cp: "38620" },
    { name: "Valverde (El Hierro)", cp: "38900" },
    { name: "San Sebastián de la Gomera", cp: "38800" },
    { name: "Breña Alta", cp: "38710" },
    { name: "Los Silos", cp: "38470" },
  ],

  // ============= CANTABRIA =============
  "39": [
    { name: "Santander", cp: "39001" },
    { name: "Torrelavega", cp: "39300" },
    { name: "Castro-Urdiales", cp: "39700" },
    { name: "Camargo", cp: "39600" },
    { name: "Piélagos", cp: "39470" },
    { name: "Laredo", cp: "39770" },
    { name: "Santoña", cp: "39740" },
    { name: "Astillero", cp: "39610" },
    { name: "Reinosa", cp: "39200" },
    { name: "Santa Cruz de Bezana", cp: "39100" },
    { name: "Los Corrales de Buelna", cp: "39400" },
    { name: "Suances", cp: "39340" },
    { name: "Cabezón de la Sal", cp: "39500" },
    { name: "Colindres", cp: "39750" },
    { name: "Comillas", cp: "39520" },
    { name: "San Vicente de la Barquera", cp: "39540" },
    { name: "Ramales de la Victoria", cp: "39800" },
    { name: "Potes", cp: "39570" },
    { name: "Medio Cudeyo", cp: "39709" },
    { name: "Santa María de Cayón", cp: "39660" },
  ],

  // ============= CASTILLA-LA MANCHA =============
  "02": [ // Albacete
    { name: "Albacete", cp: "02001" },
    { name: "Hellín", cp: "02400" },
    { name: "Villarrobledo", cp: "02600" },
    { name: "Almansa", cp: "02640" },
    { name: "La Roda", cp: "02630" },
    { name: "Caudete", cp: "02660" },
    { name: "Tobarra", cp: "02500" },
    { name: "Madrigueras", cp: "02230" },
    { name: "Casas Ibáñez", cp: "02200" },
    { name: "Tarazona de la Mancha", cp: "02100" },
    { name: "Villamalea", cp: "02270" },
    { name: "Chinchilla de Monte-Aragón", cp: "02520" },
    { name: "Yeste", cp: "02480" },
    { name: "Elche de la Sierra", cp: "02430" },
  ],
  "13": [ // Ciudad Real
    { name: "Ciudad Real", cp: "13001" },
    { name: "Puertollano", cp: "13500" },
    { name: "Tomelloso", cp: "13700" },
    { name: "Alcázar de San Juan", cp: "13600" },
    { name: "Valdepeñas", cp: "13300" },
    { name: "Manzanares", cp: "13200" },
    { name: "Daimiel", cp: "13250" },
    { name: "La Solana", cp: "13240" },
    { name: "Miguelturra", cp: "13170" },
    { name: "Bolaños de Calatrava", cp: "13260" },
    { name: "Campo de Criptana", cp: "13610" },
    { name: "Socuéllamos", cp: "13630" },
    { name: "Villarrubia de los Ojos", cp: "13670" },
    { name: "Argamasilla de Calatrava", cp: "13440" },
    { name: "Almagro", cp: "13270" },
    { name: "Pedro Muñoz", cp: "13620" },
    { name: "Membrilla", cp: "13230" },
    { name: "Calzada de Calatrava", cp: "13370" },
    { name: "Almodóvar del Campo", cp: "13580" },
    { name: "Herencia", cp: "13640" },
  ],
  "16": [ // Cuenca
    { name: "Cuenca", cp: "16001" },
    { name: "Tarancón", cp: "16400" },
    { name: "San Clemente", cp: "16600" },
    { name: "Motilla del Palancar", cp: "16200" },
    { name: "Quintanar del Rey", cp: "16220" },
    { name: "Iniesta", cp: "16235" },
    { name: "Las Pedroñeras", cp: "16660" },
    { name: "Mota del Cuervo", cp: "16630" },
    { name: "Cañete", cp: "16300" },
    { name: "Sisante", cp: "16630" },
    { name: "Belmonte", cp: "16640" },
    { name: "Horcajo de Santiago", cp: "16410" },
  ],
  "19": [ // Guadalajara
    { name: "Guadalajara", cp: "19001" },
    { name: "Azuqueca de Henares", cp: "19200" },
    { name: "Alovera", cp: "19208" },
    { name: "Cabanillas del Campo", cp: "19171" },
    { name: "Sigüenza", cp: "19250" },
    { name: "Marchamalo", cp: "19180" },
    { name: "Yunquera de Henares", cp: "19210" },
    { name: "El Casar", cp: "19170" },
    { name: "Villanueva de la Torre", cp: "19209" },
    { name: "Molina de Aragón", cp: "19300" },
    { name: "Pastrana", cp: "19100" },
    { name: "Brihuega", cp: "19400" },
    { name: "Sacedón", cp: "19120" },
    { name: "Chiloeches", cp: "19160" },
  ],
  "45": [ // Toledo
    { name: "Toledo", cp: "45001" },
    { name: "Talavera de la Reina", cp: "45600" },
    { name: "Illescas", cp: "45200" },
    { name: "Seseña", cp: "45223" },
    { name: "Torrijos", cp: "45500" },
    { name: "Yuncos", cp: "45210" },
    { name: "Ocaña", cp: "45300" },
    { name: "Consuegra", cp: "45700" },
    { name: "Mora", cp: "45400" },
    { name: "Madridejos", cp: "45710" },
    { name: "Sonseca", cp: "45100" },
    { name: "Quintanar de la Orden", cp: "45800" },
    { name: "La Puebla de Montalbán", cp: "45516" },
    { name: "Ugena", cp: "45217" },
    { name: "Numancia de la Sagra", cp: "45230" },
    { name: "Bargas", cp: "45593" },
    { name: "Olías del Rey", cp: "45280" },
    { name: "Cobeja", cp: "45222" },
    { name: "Esquivias", cp: "45221" },
    { name: "Yepes", cp: "45313" },
    { name: "Villacañas", cp: "45860" },
    { name: "Camarena", cp: "45180" },
    { name: "Fuensalida", cp: "45510" },
    { name: "Méntrida", cp: "45930" },
  ],

  // ============= CASTILLA Y LEÓN =============
  "05": [ // Ávila
    { name: "Ávila", cp: "05001" },
    { name: "Arévalo", cp: "05200" },
    { name: "Arenas de San Pedro", cp: "05400" },
    { name: "Las Navas del Marqués", cp: "05230" },
    { name: "Sotillo de la Adrada", cp: "05420" },
    { name: "Cebreros", cp: "05260" },
    { name: "El Tiemblo", cp: "05270" },
    { name: "Candeleda", cp: "05480" },
    { name: "El Barco de Ávila", cp: "05600" },
    { name: "Madrigal de las Altas Torres", cp: "05220" },
  ],
  "09": [ // Burgos
    { name: "Burgos", cp: "09001" },
    { name: "Miranda de Ebro", cp: "09200" },
    { name: "Aranda de Duero", cp: "09400" },
    { name: "Briviesca", cp: "09240" },
    { name: "Medina de Pomar", cp: "09500" },
    { name: "Villarcayo", cp: "09550" },
    { name: "Lerma", cp: "09340" },
    { name: "Salas de los Infantes", cp: "09600" },
    { name: "Roa", cp: "09300" },
    { name: "Belorado", cp: "09250" },
    { name: "Espinosa de los Monteros", cp: "09560" },
    { name: "Quintanar de la Sierra", cp: "09670" },
  ],
  "24": [ // León
    { name: "León", cp: "24001" },
    { name: "Ponferrada", cp: "24400" },
    { name: "San Andrés del Rabanedo", cp: "24010" },
    { name: "Astorga", cp: "24700" },
    { name: "La Bañeza", cp: "24750" },
    { name: "Villaquilambre", cp: "24193" },
    { name: "Bembibre", cp: "24300" },
    { name: "Villablino", cp: "24100" },
    { name: "Cistierna", cp: "24800" },
    { name: "Valencia de Don Juan", cp: "24200" },
    { name: "Sahagún", cp: "24320" },
    { name: "Carrizo", cp: "24270" },
    { name: "Toral de los Vados", cp: "24560" },
    { name: "Sariegos", cp: "24121" },
  ],
  "34": [ // Palencia
    { name: "Palencia", cp: "34001" },
    { name: "Aguilar de Campoo", cp: "34800" },
    { name: "Guardo", cp: "34880" },
    { name: "Venta de Baños", cp: "34200" },
    { name: "Carrión de los Condes", cp: "34120" },
    { name: "Saldaña", cp: "34100" },
    { name: "Dueñas", cp: "34210" },
    { name: "Villamuriel de Cerrato", cp: "34190" },
    { name: "Paredes de Nava", cp: "34300" },
    { name: "Cervera de Pisuerga", cp: "34840" },
  ],
  "37": [ // Salamanca
    { name: "Salamanca", cp: "37001" },
    { name: "Béjar", cp: "37700" },
    { name: "Ciudad Rodrigo", cp: "37500" },
    { name: "Santa Marta de Tormes", cp: "37900" },
    { name: "Villares de la Reina", cp: "37184" },
    { name: "Carbajosa de la Sagrada", cp: "37188" },
    { name: "Villamayor", cp: "37185" },
    { name: "Guijuelo", cp: "37770" },
    { name: "Peñaranda de Bracamonte", cp: "37300" },
    { name: "Vitigudino", cp: "37210" },
    { name: "Alba de Tormes", cp: "37800" },
    { name: "Cabrerizos", cp: "37193" },
    { name: "Castellanos de Moriscos", cp: "37439" },
  ],
  "40": [ // Segovia
    { name: "Segovia", cp: "40001" },
    { name: "Cuéllar", cp: "40200" },
    { name: "El Espinar", cp: "40400" },
    { name: "San Ildefonso", cp: "40100" },
    { name: "Cantalejo", cp: "40320" },
    { name: "Nava de la Asunción", cp: "40450" },
    { name: "Riaza", cp: "40500" },
    { name: "Sepúlveda", cp: "40300" },
    { name: "Carbonero el Mayor", cp: "40270" },
    { name: "Coca", cp: "40480" },
  ],
  "42": [ // Soria
    { name: "Soria", cp: "42001" },
    { name: "Almazán", cp: "42200" },
    { name: "El Burgo de Osma", cp: "42300" },
    { name: "Ólvega", cp: "42110" },
    { name: "Ágreda", cp: "42100" },
    { name: "San Esteban de Gormaz", cp: "42330" },
    { name: "Covaleda", cp: "42157" },
    { name: "Vinuesa", cp: "42150" },
    { name: "Berlanga de Duero", cp: "42360" },
  ],
  "47": [ // Valladolid
    { name: "Valladolid", cp: "47001" },
    { name: "Medina del Campo", cp: "47400" },
    { name: "Laguna de Duero", cp: "47140" },
    { name: "Arroyo de la Encomienda", cp: "47195" },
    { name: "Tordesillas", cp: "47100" },
    { name: "Íscar", cp: "47420" },
    { name: "Peñafiel", cp: "47300" },
    { name: "Medina de Rioseco", cp: "47800" },
    { name: "Cigales", cp: "47270" },
    { name: "Tudela de Duero", cp: "47320" },
    { name: "Boecillo", cp: "47151" },
    { name: "Simancas", cp: "47130" },
    { name: "Zaratán", cp: "47610" },
    { name: "La Cistérniga", cp: "47193" },
    { name: "Olmedo", cp: "47410" },
    { name: "Valoria la Buena", cp: "47200" },
  ],
  "49": [ // Zamora
    { name: "Zamora", cp: "49001" },
    { name: "Benavente", cp: "49600" },
    { name: "Toro", cp: "49800" },
    { name: "Morales del Vino", cp: "49700" },
    { name: "Fuentesaúco", cp: "49400" },
    { name: "Villaralbo", cp: "49159" },
    { name: "Puebla de Sanabria", cp: "49300" },
    { name: "Alcañices", cp: "49500" },
    { name: "Coreses", cp: "49530" },
  ],

  // ============= CATALUÑA =============
  "08": [ // Barcelona
    // — Barcelona capital: distritos centrales —
    { name: "Barcelona · Ciutat Vella", cp: "08001" },
    { name: "Barcelona · L'Eixample", cp: "08010" },
    { name: "Barcelona · Gràcia", cp: "08012" },
    { name: "Barcelona · Sants-Montjuïc", cp: "08014" },
    { name: "Barcelona · Sant Martí", cp: "08018" },
    { name: "Barcelona · Sarrià-Sant Gervasi", cp: "08017" },
    { name: "Barcelona · Les Corts", cp: "08028" },
    // — Barcelona capital: distritos periféricos —
    { name: "Barcelona · Horta-Guinardó", cp: "08035" },
    { name: "Barcelona · Nou Barris", cp: "08016" },
    { name: "Barcelona · Sant Andreu", cp: "08030" },
    { name: "L'Hospitalet de Llobregat", cp: "08901" },
    { name: "Badalona", cp: "08911" },
    { name: "Terrassa", cp: "08221" },
    { name: "Sabadell", cp: "08201" },
    { name: "Mataró", cp: "08301" },
    { name: "Santa Coloma de Gramenet", cp: "08921" },
    { name: "Cornellà de Llobregat", cp: "08940" },
    { name: "Sant Boi de Llobregat", cp: "08830" },
    { name: "Granollers", cp: "08400" },
    { name: "Vilanova i la Geltrú", cp: "08800" },
    { name: "Manresa", cp: "08240" },
    { name: "Rubí", cp: "08191" },
    { name: "Castelldefels", cp: "08860" },
    { name: "El Prat de Llobregat", cp: "08820" },
    { name: "Vic", cp: "08500" },
    { name: "Igualada", cp: "08700" },
    { name: "Viladecans", cp: "08840" },
    { name: "Sant Cugat del Vallès", cp: "08172" },
    { name: "Cerdanyola del Vallès", cp: "08290" },
    { name: "Mollet del Vallès", cp: "08100" },
    { name: "Esplugues de Llobregat", cp: "08950" },
    { name: "Gavà", cp: "08850" },
    { name: "Sant Adrià de Besòs", cp: "08930" },
    { name: "Sant Feliu de Llobregat", cp: "08980" },
    { name: "Barberà del Vallès", cp: "08210" },
    { name: "Ripollet", cp: "08291" },
    { name: "Montcada i Reixac", cp: "08110" },
    { name: "Sant Joan Despí", cp: "08970" },
    { name: "Pineda de Mar", cp: "08397" },
    { name: "Sitges", cp: "08870" },
    { name: "Calella", cp: "08370" },
    { name: "Premià de Mar", cp: "08330" },
    { name: "Vilafranca del Penedès", cp: "08720" },
    { name: "Olesa de Montserrat", cp: "08640" },
    { name: "Esparreguera", cp: "08292" },
    { name: "Martorell", cp: "08760" },
    { name: "Santa Perpètua de Mogoda", cp: "08130" },
    { name: "Sant Vicenç dels Horts", cp: "08620" },
    { name: "Molins de Rei", cp: "08750" },
    { name: "Berga", cp: "08600" },
    { name: "Malgrat de Mar", cp: "08380" },
    { name: "El Masnou", cp: "08320" },
    { name: "Tordera", cp: "08490" },
    { name: "Parets del Vallès", cp: "08150" },
    { name: "Caldes de Montbui", cp: "08140" },
    { name: "Canovelles", cp: "08420" },
    { name: "La Garriga", cp: "08530" },
    { name: "Cardedeu", cp: "08440" },
    { name: "Sant Pere de Ribes", cp: "08810" },
  ],
  "17": [ // Girona
    { name: "Girona", cp: "17001" },
    { name: "Figueres", cp: "17600" },
    { name: "Blanes", cp: "17300" },
    { name: "Lloret de Mar", cp: "17310" },
    { name: "Olot", cp: "17800" },
    { name: "Salt", cp: "17190" },
    { name: "Palafrugell", cp: "17200" },
    { name: "Sant Feliu de Guíxols", cp: "17220" },
    { name: "Banyoles", cp: "17820" },
    { name: "Roses", cp: "17480" },
    { name: "Palamós", cp: "17230" },
    { name: "Castell-Platja d'Aro", cp: "17250" },
    { name: "Ripoll", cp: "17500" },
    { name: "La Bisbal d'Empordà", cp: "17100" },
    { name: "Cassà de la Selva", cp: "17244" },
    { name: "Sant Joan de les Abadesses", cp: "17860" },
    { name: "Puigcerdà", cp: "17520" },
    { name: "Torroella de Montgrí", cp: "17257" },
    { name: "L'Escala", cp: "17130" },
  ],
  "25": [ // Lleida
    { name: "Lleida", cp: "25001" },
    { name: "Balaguer", cp: "25600" },
    { name: "Tàrrega", cp: "25300" },
    { name: "Mollerussa", cp: "25230" },
    { name: "La Seu d'Urgell", cp: "25700" },
    { name: "Cervera", cp: "25200" },
    { name: "Solsona", cp: "25280" },
    { name: "Tremp", cp: "25620" },
    { name: "Les Borges Blanques", cp: "25400" },
    { name: "Almacelles", cp: "25100" },
    { name: "Alcarràs", cp: "25180" },
    { name: "Vielha e Mijaran", cp: "25530" },
    { name: "Pont de Suert", cp: "25520" },
    { name: "Sort", cp: "25560" },
    { name: "Agramunt", cp: "25310" },
  ],
  "43": [ // Tarragona
    { name: "Tarragona", cp: "43001" },
    { name: "Reus", cp: "43201" },
    { name: "Tortosa", cp: "43500" },
    { name: "El Vendrell", cp: "43700" },
    { name: "Cambrils", cp: "43850" },
    { name: "Salou", cp: "43840" },
    { name: "Valls", cp: "43800" },
    { name: "Amposta", cp: "43870" },
    { name: "Calafell", cp: "43820" },
    { name: "Vila-seca", cp: "43480" },
    { name: "Sant Carles de la Ràpita", cp: "43540" },
    { name: "Deltebre", cp: "43580" },
    { name: "Ulldecona", cp: "43550" },
    { name: "Móra d'Ebre", cp: "43740" },
    { name: "Falset", cp: "43730" },
    { name: "Montblanc", cp: "43400" },
    { name: "Torredembarra", cp: "43830" },
    { name: "L'Hospitalet de l'Infant", cp: "43890" },
    { name: "Constantí", cp: "43120" },
    { name: "L'Aldea", cp: "43896" },
  ],

  // ============= C. VALENCIANA =============
  "03": [ // Alicante
    { name: "Alicante", cp: "03001" },
    { name: "Elche", cp: "03201" },
    { name: "Torrevieja", cp: "03180" },
    { name: "Orihuela", cp: "03300" },
    { name: "Benidorm", cp: "03501" },
    { name: "Alcoy", cp: "03801" },
    { name: "San Vicente del Raspeig", cp: "03690" },
    { name: "Elda", cp: "03600" },
    { name: "Dénia", cp: "03700" },
    { name: "Petrer", cp: "03610" },
    { name: "Villena", cp: "03400" },
    { name: "Santa Pola", cp: "03130" },
    { name: "Calp", cp: "03710" },
    { name: "Jávea (Xàbia)", cp: "03730" },
    { name: "Crevillent", cp: "03330" },
    { name: "La Vila Joiosa", cp: "03570" },
    { name: "Pilar de la Horadada", cp: "03190" },
    { name: "Altea", cp: "03590" },
    { name: "Ibi", cp: "03440" },
    { name: "Mutxamel", cp: "03110" },
    { name: "Sant Joan d'Alacant", cp: "03550" },
    { name: "Aspe", cp: "03680" },
    { name: "Novelda", cp: "03660" },
    { name: "Almoradí", cp: "03160" },
    { name: "Callosa de Segura", cp: "03360" },
    { name: "Rojales", cp: "03170" },
    { name: "Guardamar del Segura", cp: "03140" },
    { name: "Catral", cp: "03158" },
    { name: "Cox", cp: "03350" },
    { name: "Albatera", cp: "03340" },
    { name: "Monforte del Cid", cp: "03670" },
    { name: "Sax", cp: "03630" },
    { name: "Banyeres de Mariola", cp: "03450" },
    { name: "El Campello", cp: "03560" },
    { name: "Teulada", cp: "03725" },
    { name: "Benissa", cp: "03720" },
    { name: "Polop", cp: "03520" },
    { name: "Finestrat", cp: "03509" },
    { name: "L'Alfàs del Pi", cp: "03580" },
    { name: "Pego", cp: "03780" },
    { name: "Ondara", cp: "03760" },
    { name: "Cocentaina", cp: "03820" },
    { name: "Muro de Alcoy", cp: "03830" },
  ],
  "12": [ // Castellón
    { name: "Castellón de la Plana", cp: "12001" },
    { name: "Vila-real", cp: "12540" },
    { name: "Burriana", cp: "12530" },
    { name: "Vinaròs", cp: "12500" },
    { name: "Benicarló", cp: "12580" },
    { name: "Onda", cp: "12200" },
    { name: "Almazora (Almassora)", cp: "12550" },
    { name: "L'Alcora", cp: "12110" },
    { name: "Segorbe", cp: "12400" },
    { name: "Nules", cp: "12520" },
    { name: "La Vall d'Uixó", cp: "12600" },
    { name: "Oropesa del Mar", cp: "12594" },
    { name: "Benicàssim", cp: "12560" },
    { name: "Peñíscola", cp: "12598" },
    { name: "Moncofa", cp: "12593" },
    { name: "Almenara", cp: "12590" },
    { name: "Sant Mateu", cp: "12170" },
    { name: "Morella", cp: "12300" },
    { name: "Alcalà de Xivert", cp: "12570" },
  ],
  "46": [ // Valencia
    // — Valencia capital: distritos centrales (Ciutat Vella y ensanche) —
    { name: "Valencia · Ciutat Vella", cp: "46001" },
    { name: "Valencia · L'Eixample", cp: "46004" },
    { name: "Valencia · Extramurs", cp: "46008" },
    { name: "Valencia · Pla del Real", cp: "46021" },
    { name: "Valencia · El Pla del Remei", cp: "46004" },
    // — Valencia capital: distritos periféricos —
    { name: "Valencia · Campanar", cp: "46015" },
    { name: "Valencia · La Saïdia", cp: "46009" },
    { name: "Valencia · Jesús", cp: "46017" },
    { name: "Valencia · Quatre Carreres", cp: "46006" },
    { name: "Valencia · Poblats Marítims", cp: "46011" },
    { name: "Valencia · Camins al Grau", cp: "46023" },
    { name: "Valencia · Algirós", cp: "46022" },
    { name: "Valencia · Benimaclet", cp: "46020" },
    { name: "Valencia · Rascanya", cp: "46019" },
    { name: "Valencia · Benicalap", cp: "46025" },
    { name: "Valencia · L'Olivereta", cp: "46018" },
    { name: "Valencia · Patraix", cp: "46014" },
    { name: "Valencia · Pobles del Nord", cp: "46016" },
    { name: "Valencia · Pobles del Sud", cp: "46012" },
    { name: "Gandía", cp: "46700" },
    { name: "Torrent", cp: "46900" },
    { name: "Paterna", cp: "46980" },
    { name: "Sagunto", cp: "46500" },
    { name: "Alzira", cp: "46600" },
    { name: "Mislata", cp: "46920" },
    { name: "Burjassot", cp: "46100" },
    { name: "Xirivella", cp: "46950" },
    { name: "Quart de Poblet", cp: "46930" },
    { name: "Manises", cp: "46940" },
    { name: "Cullera", cp: "46400" },
    { name: "Xàtiva", cp: "46800" },
    { name: "Ontinyent", cp: "46870" },
    { name: "Aldaia", cp: "46960" },
    { name: "Alaquàs", cp: "46970" },
    { name: "Catarroja", cp: "46470" },
    { name: "Sueca", cp: "46410" },
    { name: "Picassent", cp: "46220" },
    { name: "Alboraya", cp: "46120" },
    { name: "Llíria", cp: "46160" },
    { name: "Oliva", cp: "46780" },
    { name: "Bétera", cp: "46117" },
    { name: "Requena", cp: "46340" },
    { name: "Massamagrell", cp: "46130" },
    { name: "Tavernes de la Valldigna", cp: "46760" },
    { name: "L'Eliana", cp: "46183" },
    { name: "Algemesí", cp: "46680" },
    { name: "Carcaixent", cp: "46740" },
    { name: "La Pobla de Vallbona", cp: "46185" },
    { name: "Silla", cp: "46460" },
    { name: "Moncada", cp: "46113" },
    { name: "Albal", cp: "46470" },
    { name: "Massanassa", cp: "46470" },
    { name: "Alfafar", cp: "46910" },
    { name: "Benaguasil", cp: "46180" },
    { name: "Bonrepòs i Mirambell", cp: "46131" },
    { name: "Alboraia", cp: "46120" },
    { name: "Pobla Llarga", cp: "46670" },
    { name: "Utiel", cp: "46300" },
    { name: "Buñol", cp: "46360" },
    { name: "Chiva", cp: "46370" },
    { name: "Cheste", cp: "46380" },
    { name: "Alfafar", cp: "46910" },
    { name: "Picanya", cp: "46210" },
    { name: "Foios", cp: "46134" },
    { name: "Meliana", cp: "46133" },
  ],

  // ============= EXTREMADURA =============
  "06": [ // Badajoz
    { name: "Badajoz", cp: "06001" },
    { name: "Mérida", cp: "06800" },
    { name: "Don Benito", cp: "06400" },
    { name: "Almendralejo", cp: "06200" },
    { name: "Villanueva de la Serena", cp: "06700" },
    { name: "Zafra", cp: "06300" },
    { name: "Olivenza", cp: "06100" },
    { name: "Montijo", cp: "06480" },
    { name: "Villafranca de los Barros", cp: "06220" },
    { name: "Jerez de los Caballeros", cp: "06380" },
    { name: "Azuaga", cp: "06920" },
    { name: "Castuera", cp: "06420" },
    { name: "Llerena", cp: "06900" },
    { name: "Fregenal de la Sierra", cp: "06340" },
    { name: "Alburquerque", cp: "06510" },
    { name: "Talavera la Real", cp: "06140" },
    { name: "Aceuchal", cp: "06207" },
    { name: "Calamonte", cp: "06810" },
    { name: "Los Santos de Maimona", cp: "06230" },
    { name: "Quintana de la Serena", cp: "06450" },
  ],
  "10": [ // Cáceres
    { name: "Cáceres", cp: "10001" },
    { name: "Plasencia", cp: "10600" },
    { name: "Navalmoral de la Mata", cp: "10300" },
    { name: "Trujillo", cp: "10200" },
    { name: "Coria", cp: "10800" },
    { name: "Miajadas", cp: "10100" },
    { name: "Moraleja", cp: "10840" },
    { name: "Jaraíz de la Vera", cp: "10400" },
    { name: "Valencia de Alcántara", cp: "10500" },
    { name: "Arroyo de la Luz", cp: "10900" },
    { name: "Logrosán", cp: "10120" },
    { name: "Hervás", cp: "10700" },
    { name: "Guadalupe", cp: "10140" },
    { name: "Casar de Cáceres", cp: "10190" },
    { name: "Talayuela", cp: "10310" },
    { name: "Montehermoso", cp: "10810" },
    { name: "Malpartida de Cáceres", cp: "10910" },
  ],

  // ============= GALICIA =============
  "15": [ // A Coruña
    { name: "A Coruña", cp: "15001" },
    { name: "Santiago de Compostela", cp: "15701" },
    { name: "Ferrol", cp: "15401" },
    { name: "Narón", cp: "15570" },
    { name: "Oleiros", cp: "15173" },
    { name: "Carballo", cp: "15100" },
    { name: "Arteixo", cp: "15142" },
    { name: "Ames", cp: "15220" },
    { name: "Culleredo", cp: "15670" },
    { name: "Cambre", cp: "15660" },
    { name: "Ribeira", cp: "15960" },
    { name: "Boiro", cp: "15930" },
    { name: "Betanzos", cp: "15300" },
    { name: "Sada", cp: "15160" },
    { name: "Bergondo", cp: "15165" },
    { name: "Cee", cp: "15270" },
    { name: "Noia", cp: "15200" },
    { name: "Padrón", cp: "15900" },
    { name: "Melide", cp: "15800" },
    { name: "Negreira", cp: "15830" },
    { name: "Ortigueira", cp: "15330" },
    { name: "As Pontes de García Rodríguez", cp: "15320" },
    { name: "Pontedeume", cp: "15600" },
    { name: "Fene", cp: "15500" },
    { name: "Mugardos", cp: "15620" },
    { name: "Teo", cp: "15883" },
    { name: "Brión", cp: "15865" },
    { name: "Muros", cp: "15250" },
    { name: "Carral", cp: "15175" },
  ],
  "27": [ // Lugo
    { name: "Lugo", cp: "27001" },
    { name: "Monforte de Lemos", cp: "27400" },
    { name: "Viveiro", cp: "27850" },
    { name: "Vilalba", cp: "27800" },
    { name: "Sarria", cp: "27600" },
    { name: "Ribadeo", cp: "27700" },
    { name: "Foz", cp: "27780" },
    { name: "Burela", cp: "27880" },
    { name: "Chantada", cp: "27500" },
    { name: "Cervo", cp: "27891" },
    { name: "Quiroga", cp: "27320" },
    { name: "Becerreá", cp: "27640" },
  ],
  "32": [ // Ourense
    { name: "Ourense", cp: "32001" },
    { name: "O Barco de Valdeorras", cp: "32300" },
    { name: "Verín", cp: "32600" },
    { name: "O Carballiño", cp: "32500" },
    { name: "A Rúa", cp: "32350" },
    { name: "Allariz", cp: "32660" },
    { name: "Xinzo de Limia", cp: "32630" },
    { name: "Ribadavia", cp: "32400" },
    { name: "Celanova", cp: "32800" },
    { name: "Maceda", cp: "32700" },
    { name: "O Pereiro de Aguiar", cp: "32710" },
  ],
  "36": [ // Pontevedra
    { name: "Pontevedra", cp: "36001" },
    { name: "Vigo", cp: "36201" },
    { name: "Redondela", cp: "36800" },
    { name: "Vilagarcía de Arousa", cp: "36600" },
    { name: "Cangas", cp: "36940" },
    { name: "Marín", cp: "36900" },
    { name: "Ponteareas", cp: "36860" },
    { name: "Lalín", cp: "36500" },
    { name: "A Estrada", cp: "36680" },
    { name: "Sanxenxo", cp: "36960" },
    { name: "O Porriño", cp: "36400" },
    { name: "Tui", cp: "36700" },
    { name: "Bueu", cp: "36930" },
    { name: "Moaña", cp: "36950" },
    { name: "Nigrán", cp: "36350" },
    { name: "Gondomar", cp: "36380" },
    { name: "Vilanova de Arousa", cp: "36620" },
    { name: "Cambados", cp: "36630" },
    { name: "Cuntis", cp: "36670" },
    { name: "Caldas de Reis", cp: "36650" },
    { name: "Mos", cp: "36415" },
    { name: "Salvaterra de Miño", cp: "36450" },
    { name: "Poio", cp: "36005" },
    { name: "Baiona", cp: "36300" },
  ],

  // ============= LA RIOJA =============
  "26": [
    { name: "Logroño", cp: "26001" },
    { name: "Calahorra", cp: "26500" },
    { name: "Arnedo", cp: "26580" },
    { name: "Haro", cp: "26200" },
    { name: "Lardero", cp: "26140" },
    { name: "Nájera", cp: "26300" },
    { name: "Alfaro", cp: "26540" },
    { name: "Santo Domingo de la Calzada", cp: "26250" },
    { name: "Villamediana de Iregua", cp: "26142" },
    { name: "Cenicero", cp: "26350" },
    { name: "Autol", cp: "26560" },
    { name: "Rincón de Soto", cp: "26550" },
    { name: "Pradejón", cp: "26510" },
    { name: "Navarrete", cp: "26370" },
    { name: "Ezcaray", cp: "26280" },
    { name: "Quel", cp: "26570" },
    { name: "Cervera del Río Alhama", cp: "26520" },
  ],

  // ============= MADRID =============
  // Estructura operativa:
  //   1) Madrid capital — 21 distritos
  //   2) Área metropolitana — Norte / Este (Corredor del Henares) / Sur / Oeste-Noroeste / Sureste
  //   3) Resto Comunidad — Sierra Norte / Sierra Noroeste / Sierra Oeste / Vegas y Sureste rural
  "28": [
    // ───── 1) Madrid capital · 21 distritos ─────
    { name: "Madrid capital · Centro", cp: "28013" },
    { name: "Madrid capital · Arganzuela", cp: "28005" },
    { name: "Madrid capital · Retiro", cp: "28009" },
    { name: "Madrid capital · Salamanca", cp: "28001" },
    { name: "Madrid capital · Chamartín", cp: "28036" },
    { name: "Madrid capital · Tetuán", cp: "28020" },
    { name: "Madrid capital · Chamberí", cp: "28010" },
    { name: "Madrid capital · Fuencarral-El Pardo", cp: "28034" },
    { name: "Madrid capital · Moncloa-Aravaca", cp: "28008" },
    { name: "Madrid capital · Latina", cp: "28011" },
    { name: "Madrid capital · Carabanchel", cp: "28019" },
    { name: "Madrid capital · Usera", cp: "28026" },
    { name: "Madrid capital · Puente de Vallecas", cp: "28038" },
    { name: "Madrid capital · Moratalaz", cp: "28030" },
    { name: "Madrid capital · Ciudad Lineal", cp: "28017" },
    { name: "Madrid capital · Hortaleza", cp: "28043" },
    { name: "Madrid capital · Villaverde", cp: "28021" },
    { name: "Madrid capital · Villa de Vallecas", cp: "28031" },
    { name: "Madrid capital · Vicálvaro", cp: "28032" },
    { name: "Madrid capital · San Blas-Canillejas", cp: "28022" },
    { name: "Madrid capital · Barajas", cp: "28042" },

    // ───── 2) Área metropolitana · Norte ─────
    { name: "Á. Metro Norte · Alcobendas", cp: "28100" },
    { name: "Á. Metro Norte · San Sebastián de los Reyes", cp: "28700" },
    { name: "Á. Metro Norte · Tres Cantos", cp: "28760" },
    { name: "Á. Metro Norte · Colmenar Viejo", cp: "28770" },
    { name: "Á. Metro Norte · Algete", cp: "28110" },

    // ───── 2) Área metropolitana · Este (Corredor del Henares) ─────
    { name: "Á. Metro Este · Coslada", cp: "28820" },
    { name: "Á. Metro Este · San Fernando de Henares", cp: "28830" },
    { name: "Á. Metro Este · Torrejón de Ardoz", cp: "28850" },
    { name: "Á. Metro Este · Alcalá de Henares", cp: "28801" },
    { name: "Á. Metro Este · Mejorada del Campo", cp: "28840" },
    { name: "Á. Metro Este · Velilla de San Antonio", cp: "28891" },
    { name: "Á. Metro Este · Paracuellos de Jarama", cp: "28860" },
    { name: "Á. Metro Este · Daganzo de Arriba", cp: "28814" },
    { name: "Á. Metro Este · Camarma de Esteruelas", cp: "28816" },
    { name: "Á. Metro Este · Meco", cp: "28880" },
    { name: "Á. Metro Este · Villalbilla", cp: "28810" },
    { name: "Á. Metro Este · Loeches", cp: "28890" },

    // ───── 2) Área metropolitana · Sur ─────
    { name: "Á. Metro Sur · Getafe", cp: "28901" },
    { name: "Á. Metro Sur · Leganés", cp: "28911" },
    { name: "Á. Metro Sur · Alcorcón", cp: "28921" },
    { name: "Á. Metro Sur · Móstoles", cp: "28931" },
    { name: "Á. Metro Sur · Fuenlabrada", cp: "28940" },
    { name: "Á. Metro Sur · Parla", cp: "28980" },
    { name: "Á. Metro Sur · Pinto", cp: "28320" },
    { name: "Á. Metro Sur · Valdemoro", cp: "28340" },
    { name: "Á. Metro Sur · Humanes de Madrid", cp: "28970" },
    { name: "Á. Metro Sur · Griñón", cp: "28971" },
    { name: "Á. Metro Sur · Cubas de la Sagra", cp: "28978" },

    // ───── 2) Área metropolitana · Oeste / Noroeste ─────
    { name: "Á. Metro Oeste · Pozuelo de Alarcón", cp: "28223" },
    { name: "Á. Metro Oeste · Majadahonda", cp: "28220" },
    { name: "Á. Metro Oeste · Las Rozas", cp: "28230" },
    { name: "Á. Metro Oeste · Boadilla del Monte", cp: "28660" },
    { name: "Á. Metro Oeste · Villaviciosa de Odón", cp: "28670" },
    { name: "Á. Metro Oeste · Collado Villalba", cp: "28400" },
    { name: "Á. Metro Oeste · Villanueva de la Cañada", cp: "28691" },
    { name: "Á. Metro Oeste · Villanueva del Pardillo", cp: "28229" },
    { name: "Á. Metro Oeste · Galapagar", cp: "28260" },
    { name: "Á. Metro Oeste · Torrelodones", cp: "28250" },
    { name: "Á. Metro Oeste · Hoyo de Manzanares", cp: "28240" },

    // ───── 2) Área metropolitana · Sureste ─────
    { name: "Á. Metro Sureste · Rivas-Vaciamadrid", cp: "28521" },
    { name: "Á. Metro Sureste · Arganda del Rey", cp: "28500" },
    { name: "Á. Metro Sureste · San Martín de la Vega", cp: "28330" },
    { name: "Á. Metro Sureste · Ciempozuelos", cp: "28350" },

    // ───── 3) Resto Comunidad · Sierra Norte ─────
    { name: "Sierra Norte · Buitrago del Lozoya", cp: "28730" },
    { name: "Sierra Norte · Lozoya", cp: "28742" },
    { name: "Sierra Norte · Rascafría", cp: "28740" },
    { name: "Sierra Norte · Torrelaguna", cp: "28180" },
    { name: "Sierra Norte · La Cabrera", cp: "28751" },
    { name: "Sierra Norte · Miraflores de la Sierra", cp: "28792" },
    { name: "Sierra Norte · Soto del Real", cp: "28791" },
    { name: "Sierra Norte · Manzanares el Real", cp: "28410" },

    // ───── 3) Resto Comunidad · Sierra Noroeste ─────
    { name: "Sierra Noroeste · Guadarrama", cp: "28440" },
    { name: "Sierra Noroeste · San Lorenzo de El Escorial", cp: "28200" },
    { name: "Sierra Noroeste · El Escorial", cp: "28280" },
    { name: "Sierra Noroeste · Cercedilla", cp: "28470" },
    { name: "Sierra Noroeste · Navacerrada", cp: "28491" },
    { name: "Sierra Noroeste · Moralzarzal", cp: "28411" },

    // ───── 3) Resto Comunidad · Sierra Oeste ─────
    { name: "Sierra Oeste · San Martín de Valdeiglesias", cp: "28680" },
    { name: "Sierra Oeste · Villa del Prado", cp: "28630" },
    { name: "Sierra Oeste · Navalcarnero", cp: "28600" },
    { name: "Sierra Oeste · Aldea del Fresno", cp: "28620" },

    // ───── 3) Resto Comunidad · Vegas / Sureste rural ─────
    { name: "Vegas / Sureste rural · Aranjuez", cp: "28300" },
    { name: "Vegas / Sureste rural · Chinchón", cp: "28370" },
    { name: "Vegas / Sureste rural · Villarejo de Salvanés", cp: "28590" },
    { name: "Vegas / Sureste rural · Colmenar de Oreja", cp: "28380" },
    { name: "Vegas / Sureste rural · Morata de Tajuña", cp: "28530" },
  ],

  // ============= MURCIA =============
  "30": [
    { name: "Murcia", cp: "30001" },
    { name: "Cartagena", cp: "30201" },
    { name: "Lorca", cp: "30800" },
    { name: "Molina de Segura", cp: "30500" },
    { name: "Alcantarilla", cp: "30820" },
    { name: "Águilas", cp: "30880" },
    { name: "Cieza", cp: "30530" },
    { name: "Yecla", cp: "30510" },
    { name: "Jumilla", cp: "30520" },
    { name: "Caravaca de la Cruz", cp: "30400" },
    { name: "Torre-Pacheco", cp: "30700" },
    { name: "San Javier", cp: "30730" },
    { name: "Mazarrón", cp: "30870" },
    { name: "San Pedro del Pinatar", cp: "30740" },
    { name: "Mula", cp: "30170" },
    { name: "Totana", cp: "30850" },
    { name: "Alhama de Murcia", cp: "30840" },
    { name: "Calasparra", cp: "30420" },
    { name: "Las Torres de Cotillas", cp: "30565" },
    { name: "Archena", cp: "30600" },
    { name: "Bullas", cp: "30180" },
    { name: "Fuente Álamo", cp: "30320" },
    { name: "Abarán", cp: "30550" },
    { name: "Santomera", cp: "30140" },
    { name: "Beniel", cp: "30130" },
    { name: "Puerto Lumbreras", cp: "30890" },
    { name: "Cehegín", cp: "30430" },
    { name: "Moratalla", cp: "30440" },
    { name: "Lorquí", cp: "30564" },
    { name: "Ceutí", cp: "30562" },
  ],

  // ============= NAVARRA =============
  "31": [
    { name: "Pamplona", cp: "31001" },
    { name: "Tudela", cp: "31500" },
    { name: "Barañáin", cp: "31010" },
    { name: "Burlada", cp: "31600" },
    { name: "Estella", cp: "31200" },
    { name: "Tafalla", cp: "31300" },
    { name: "Zizur Mayor", cp: "31180" },
    { name: "Ansoáin", cp: "31013" },
    { name: "Villava", cp: "31610" },
    { name: "Berriozar", cp: "31013" },
    { name: "Sangüesa", cp: "31400" },
    { name: "Peralta", cp: "31350" },
    { name: "Cintruénigo", cp: "31592" },
    { name: "Corella", cp: "31591" },
    { name: "Lodosa", cp: "31580" },
    { name: "Castejón", cp: "31590" },
    { name: "Olite", cp: "31390" },
    { name: "Alsasua", cp: "31800" },
    { name: "Aoiz", cp: "31430" },
    { name: "Huarte", cp: "31620" },
    { name: "Noáin", cp: "31110" },
    { name: "Cizur", cp: "31190" },
    { name: "Mendavia", cp: "31587" },
    { name: "Marcilla", cp: "31340" },
    { name: "Valtierra", cp: "31514" },
  ],

  // ============= PAÍS VASCO =============
  "01": [ // Álava
    { name: "Vitoria-Gasteiz", cp: "01001" },
    { name: "Llodio", cp: "01400" },
    { name: "Amurrio", cp: "01470" },
    { name: "Salvatierra (Agurain)", cp: "01200" },
    { name: "Laudio", cp: "01400" },
    { name: "Ayala (Aiara)", cp: "01476" },
    { name: "Iruña Oka", cp: "01230" },
    { name: "Oyón (Oion)", cp: "01320" },
    { name: "Alegría-Dulantzi", cp: "01240" },
    { name: "Laguardia", cp: "01300" },
    { name: "Labastida", cp: "01330" },
  ],
  "20": [ // Gipuzkoa
    { name: "San Sebastián (Donostia)", cp: "20001" },
    { name: "Irún", cp: "20301" },
    { name: "Errenteria", cp: "20100" },
    { name: "Eibar", cp: "20600" },
    { name: "Zarautz", cp: "20800" },
    { name: "Hernani", cp: "20120" },
    { name: "Tolosa", cp: "20400" },
    { name: "Arrasate (Mondragón)", cp: "20500" },
    { name: "Bergara", cp: "20570" },
    { name: "Andoain", cp: "20140" },
    { name: "Pasaia", cp: "20110" },
    { name: "Lasarte-Oria", cp: "20160" },
    { name: "Beasain", cp: "20200" },
    { name: "Azkoitia", cp: "20720" },
    { name: "Azpeitia", cp: "20730" },
    { name: "Oñati", cp: "20560" },
    { name: "Zumarraga", cp: "20700" },
    { name: "Urnieta", cp: "20130" },
    { name: "Lezo", cp: "20100" },
    { name: "Oiartzun", cp: "20180" },
    { name: "Hondarribia", cp: "20280" },
    { name: "Usurbil", cp: "20170" },
    { name: "Ordizia", cp: "20240" },
    { name: "Zumaia", cp: "20750" },
    { name: "Getaria", cp: "20808" },
    { name: "Deba", cp: "20820" },
    { name: "Mutriku", cp: "20830" },
    { name: "Soraluze", cp: "20590" },
  ],
  "48": [ // Bizkaia
    // — Bilbao capital: distritos centrales —
    { name: "Bilbao · Abando", cp: "48001" },
    { name: "Bilbao · Casco Viejo (Ibaiondo)", cp: "48005" },
    { name: "Bilbao · Indautxu", cp: "48010" },
    { name: "Bilbao · Begoña", cp: "48006" },
    // — Bilbao capital: distritos periféricos —
    { name: "Bilbao · Deusto", cp: "48014" },
    { name: "Bilbao · Uribarri", cp: "48007" },
    { name: "Bilbao · Errekalde", cp: "48012" },
    { name: "Bilbao · Basurto-Zorroza", cp: "48013" },
    { name: "Bilbao · Otxarkoaga-Txurdinaga", cp: "48004" },
    { name: "Barakaldo", cp: "48901" },
    { name: "Getxo", cp: "48930" },
    { name: "Portugalete", cp: "48920" },
    { name: "Santurtzi", cp: "48980" },
    { name: "Basauri", cp: "48970" },
    { name: "Leioa", cp: "48940" },
    { name: "Durango", cp: "48200" },
    { name: "Galdakao", cp: "48960" },
    { name: "Sestao", cp: "48910" },
    { name: "Erandio", cp: "48950" },
    { name: "Sopelana", cp: "48600" },
    { name: "Amorebieta-Etxano", cp: "48340" },
    { name: "Ermua", cp: "48260" },
    { name: "Mungia", cp: "48100" },
    { name: "Bermeo", cp: "48370" },
    { name: "Gernika-Lumo", cp: "48300" },
    { name: "Markina-Xemein", cp: "48270" },
    { name: "Arrigorriaga", cp: "48480" },
    { name: "Iurreta", cp: "48215" },
    { name: "Ondarroa", cp: "48700" },
    { name: "Lekeitio", cp: "48280" },
    { name: "Zalla", cp: "48860" },
    { name: "Balmaseda", cp: "48800" },
    { name: "Güeñes", cp: "48840" },
    { name: "Sopuerta", cp: "48190" },
    { name: "Berriz", cp: "48240" },
    { name: "Etxebarri", cp: "48450" },
    { name: "Berango", cp: "48640" },
    { name: "Plentzia", cp: "48620" },
  ],

  // ============= CEUTA Y MELILLA =============
  "51": [{ name: "Ceuta", cp: "51001" }],
  "52": [{ name: "Melilla", cp: "52001" }],
};

export const localidadesByProvincia = (code: string): Localidad[] =>
  LOCALIDADES_BY_PROVINCE[code] ?? [];

/** Llave única estable para una localidad (provincia + nombre) */
export const localidadKey = (provinciaCode: string, name: string) =>
  `${provinciaCode}::${name}`;

// ============================================================
//  AGRUPACIÓN JERÁRQUICA DE LOCALIDADES (nivel 1 → nivel 2)
// ============================================================
// Mapa de prefijo (parte antes del primer " · ") a su jerarquía operativa.
// Si un prefijo no está en el mapa, se trata como un grupo plano de nivel 1
// con el propio prefijo y sin subgrupo.

export interface LocalityGrouping {
  level1: string; // ej. "Área Metropolitana"
  level2?: string; // ej. "Norte"
}

const PREFIX_GROUPING: Record<string, LocalityGrouping> = {
  // ─── Madrid (28) ───
  "Madrid capital": { level1: "Madrid capital" },
  "Á. Metro Norte": { level1: "Área Metropolitana", level2: "Norte" },
  "Á. Metro Este": { level1: "Área Metropolitana", level2: "Este / Corredor del Henares" },
  "Á. Metro Sur": { level1: "Área Metropolitana", level2: "Sur" },
  "Á. Metro Oeste": { level1: "Área Metropolitana", level2: "Oeste / Noroeste" },
  "Á. Metro Sureste": { level1: "Área Metropolitana", level2: "Sureste" },
  "Sierra Norte": { level1: "Resto de Comunidad", level2: "Sierra Norte" },
  "Sierra Noroeste": { level1: "Resto de Comunidad", level2: "Sierra Noroeste" },
  "Sierra Oeste": { level1: "Resto de Comunidad", level2: "Sierra Oeste" },
  "Vegas / Sureste rural": { level1: "Resto de Comunidad", level2: "Vegas / Sureste rural" },

  // ─── Sevilla (41) ───
  "Sevilla Capital": { level1: "Sevilla Capital" },
  "SE Á. Metro Norte": { level1: "Área metropolitana", level2: "Norte" },
  "SE Á. Metro Oeste": { level1: "Área metropolitana", level2: "Oeste / Aljarafe" },
  "SE Á. Metro Sur": { level1: "Área metropolitana", level2: "Sur" },
  "SE Á. Metro Este": { level1: "Área metropolitana", level2: "Este" },
  "SE Sierra Norte": { level1: "Resto provincia Sevilla", level2: "Sierra Norte" },
  "SE Campiña Este": { level1: "Resto provincia Sevilla", level2: "Campiña / Este" },
  "SE Sur Profundo": { level1: "Resto provincia Sevilla", level2: "Sur profundo" },

  // ─── Almería (04) ───
  "Almería Capital": { level1: "Almería capital" },
  "AL Á. Metro Poniente": { level1: "Área metropolitana", level2: "Poniente cercano" },
  "AL Á. Metro Norte": { level1: "Área metropolitana", level2: "Norte / área cercana" },
  "AL Poniente Ampliado": { level1: "Resto provincia de Almería", level2: "Poniente ampliado (25–40 km)" },
  "AL Levante": { level1: "Resto provincia de Almería", level2: "Levante" },
  "AL Interior": { level1: "Resto provincia de Almería", level2: "Interior" },

  // ─── Cádiz (11) ───
  "Cádiz Capital": { level1: "Cádiz capital" },
  "CA Á. Metro Bahía": { level1: "Área metropolitana", level2: "Bahía de Cádiz" },
  "CA Jerez": { level1: "Resto provincia de Cádiz", level2: "Jerez" },
  "CA Costa Noroeste": { level1: "Resto provincia de Cádiz", level2: "Costa noroeste" },
  "CA Campo de Gibraltar": { level1: "Resto provincia de Cádiz", level2: "Campo de Gibraltar" },

  // ─── Córdoba (14) ───
  "Córdoba Capital": { level1: "Córdoba capital" },
  "CO Á. Metro Oeste": { level1: "Área metropolitana", level2: "Oeste / Valle del Guadalquivir" },
  "CO Á. Metro Sur": { level1: "Área metropolitana", level2: "Sur cercano" },
  "CO Á. Metro Este": { level1: "Área metropolitana", level2: "Este cercano" },
  "CO Subbética": { level1: "Resto provincia de Córdoba", level2: "Sur (Subbética)" },
  "CO Campiña": { level1: "Resto provincia de Córdoba", level2: "Campiña" },
  "CO Norte": { level1: "Resto provincia de Córdoba", level2: "Norte (Los Pedroches / Valle del Guadiato)" },

  // ─── Granada (18) ───
  "Granada Capital": { level1: "Granada capital" },
  "GR Á. Metro Oeste": { level1: "Área metropolitana", level2: "Cinturón Oeste" },
  "GR Á. Metro Sur": { level1: "Área metropolitana", level2: "Cinturón Sur" },
  "GR Á. Metro Norte": { level1: "Área metropolitana", level2: "Cinturón Norte" },
  "GR Costa Tropical": { level1: "Resto provincia de Granada", level2: "Costa Tropical" },
  "GR Norte Interior": { level1: "Resto provincia de Granada", level2: "Norte / interior" },
  "GR Alpujarra": { level1: "Resto provincia de Granada", level2: "Alpujarra" },

  // ─── Huelva (21) ───
  "Huelva Capital": { level1: "Huelva capital" },
  "HU Á. Metro Cercano": { level1: "Área metropolitana", level2: "Cinturón cercano" },
  "HU Costa": { level1: "Resto provincia de Huelva", level2: "Costa" },
  "HU Condado": { level1: "Resto provincia de Huelva", level2: "Condado" },
  "HU Sierra": { level1: "Resto provincia de Huelva", level2: "Sierra" },

  // ─── Jaén (23) ───
  "Jaén Capital": { level1: "Jaén capital" },
  "JA Á. Metro Cercano": { level1: "Área metropolitana", level2: "Cinturón cercano" },
  "JA Corredor Central": { level1: "Resto provincia de Jaén", level2: "Corredor central" },
  "JA La Loma": { level1: "Resto provincia de Jaén", level2: "La Loma" },
  "JA Sierra": { level1: "Resto provincia de Jaén", level2: "Sierra" },
};

export interface LocalitySubgroup {
  key: string; // identificador estable: "L1" o "L1::L2"
  level2: string | null; // null cuando es un grupo plano
  localidades: Localidad[];
}

export interface LocalityGroup {
  key: string; // nivel 1
  level1: string;
  hasSubgroups: boolean;
  subgroups: LocalitySubgroup[]; // si hasSubgroups=false → un único subgrupo con level2=null
  localidades: Localidad[]; // todas las localidades de este nivel 1 (atajo)
}

/**
 * Devuelve las localidades de una provincia agrupadas en hasta 2 niveles
 * jerárquicos a partir del prefijo `"Grupo · Localidad"` o
 * `"Grupo · Sub · Localidad"`. Para provincias sin prefijos reconocibles,
 * devuelve un único grupo "Localidades" plano.
 */
export const getGroupedLocalidades = (provinciaCode: string): LocalityGroup[] => {
  const list = LOCALIDADES_BY_PROVINCE[provinciaCode] ?? [];
  if (list.length === 0) return [];

  const byL1 = new Map<string, Map<string | "__flat__", Localidad[]>>();

  for (const loc of list) {
    const sepIdx = loc.name.indexOf(" · ");
    let l1 = "Localidades";
    let l2: string | null = null;
    if (sepIdx >= 0) {
      const prefix = loc.name.slice(0, sepIdx);
      const grouping = PREFIX_GROUPING[prefix];
      if (grouping) {
        l1 = grouping.level1;
        l2 = grouping.level2 ?? null;
      } else {
        l1 = prefix;
      }
    }
    if (!byL1.has(l1)) byL1.set(l1, new Map());
    const subMap = byL1.get(l1)!;
    const subKey = l2 ?? "__flat__";
    if (!subMap.has(subKey)) subMap.set(subKey, []);
    subMap.get(subKey)!.push(loc);
  }

  const groups: LocalityGroup[] = [];
  for (const [l1, subMap] of byL1) {
    const subgroups: LocalitySubgroup[] = [];
    let hasSubgroups = false;
    const allLocs: Localidad[] = [];
    for (const [subKey, locs] of subMap) {
      const level2 = subKey === "__flat__" ? null : (subKey as string);
      if (level2) hasSubgroups = true;
      subgroups.push({
        key: level2 ? `${l1}::${level2}` : l1,
        level2,
        localidades: locs,
      });
      allLocs.push(...locs);
    }
    groups.push({
      key: l1,
      level1: l1,
      hasSubgroups,
      subgroups,
      localidades: allLocs,
    });
  }
  return groups;
};
